### PR TITLE
Updated devops course FAQ

### PR DESCRIPTION
**Pull request by 95Rawan**
Updated DevOps course FAQ by correcting some mistakes, removing duplicated sentences, and adding youtube playlists links for easier access.

### CODE REVIEW

**Comment by 95Rawan** [comment]
You're very welcome :)

**Comment by 95Rawan** [comment]
I noticed that question 9 might have not been answered correctly. I think they were asking about after finishing the course if there are any certificates they can take(like when you take AWS certifications after studying the material) and not if you provide any certificates after the course.

**Comment by 95Rawan** [comment]
Thanks a lot.

**Comment by 95Rawan** [comment]
Thanks for the information.

**Review by RehabAbotalep — APPROVED** [review]

**Pull request merged**
